// Gabriel Seethor, A0257008H
import React from "react";
import { render, screen, act, waitFor } from "@testing-library/react";
import { MemoryRouter, Routes, Route } from "react-router-dom";
import axios from "axios";
import ProductDetails from "../pages/ProductDetails";

//Generated by AI To Serve as a teaching point/tutorial for learning
//Attribution: This file is prepared with the help of DeepSeek-V3.2
// Mock axios
jest.mock("axios");

// Mock context hooks
jest.mock("../context/auth", () => ({
  useAuth: jest.fn(() => [null, jest.fn()]),
}));

const mockSetCart = jest.fn();

jest.mock("../context/cart", () => ({
  useCart: jest.fn(() => [[], mockSetCart]),
}));
jest.mock("../context/search", () => ({
  useSearch: jest.fn(() => [{ keyword: "" }, jest.fn()]),
}));

jest.mock("../hooks/useCategory", () => ({
  __esModule: true,
  default: jest.fn(() => [
    [
      { _id: "cat1", name: "Electronics", slug: "electronics" },
      { _id: "cat2", name: "Books", slug: "books" },
      { _id: "cat3", name: "Clothing", slug: "clothing" },
    ],
    jest.fn(),
  ]),
}));

// Gabriel Seethor, A0257008H
describe("Product Details Integration Tests", () => {
  const mockProduct = {
    _id: "123",
    name: "Test Product",
    description: "Test Description",
    price: 100,
    category: { _id: "cat1", name: "Electronics" },
    slug: "test-product",
    quantity: 50,
  };

  const mockSimilarProducts = [
    {
      _id: "456",
      name: "Similar Product",
      description: "Similar Description",
      price: 150,
      slug: "similar-product",
      quantity: 50,
    },
  ];

  beforeEach(() => {
    jest.clearAllMocks();
  });

  it("should show loading state before product details are loaded", async () => {
    // Create promises we can resolve later
    let resolveProductCall;
    let resolveCategoryCall;

    const productPromise = new Promise((resolve) => {
      resolveProductCall = resolve;
    });

    const categoryPromise = new Promise((resolve) => {
      resolveCategoryCall = resolve;
    });

    // Mock axios calls
    axios.get.mockImplementation((url) => {
      if (url.includes("/api/v1/product/get-product/")) {
        return productPromise;
      }
      if (url.includes("/api/v1/category/get-category")) {
        return categoryPromise;
      }
      return Promise.reject(new Error("Not mocked"));
    });

    render(
      <MemoryRouter initialEntries={["/product/test-product"]}>
        <Routes>
          <Route path="/product/:slug" element={<ProductDetails />} />
        </Routes>
      </MemoryRouter>,
    );

    // Check loading state
    const loadingMessages = screen.getAllByText(/Loading.../i);
    expect(loadingMessages[0]).toBeInTheDocument();

    // Resolve the category call (for Header/Layout)
    await act(async () => {
      resolveCategoryCall({ data: { category: [] } });
      await Promise.resolve();
    });

    // Resolve the product call
    await act(async () => {
      resolveProductCall({
        data: {
          product: mockProduct,
          success: true,
        },
      });

      // Mock the similar products call
      axios.get.mockResolvedValueOnce({
        data: { products: mockSimilarProducts },
      });

      await Promise.resolve();
    });

    // Wait for loading to disappear and product to appear
    //waitFor => keeps checking
    await waitFor(() => {
      expect(screen.queryByText(/Loading.../i)).not.toBeInTheDocument();
    });

    // Check product details are rendered
    expect(screen.getByText("Product Details")).toBeInTheDocument();
    expect(screen.getByText(`Name : ${mockProduct.name}`)).toBeInTheDocument();
    expect(
      screen.getByText(`Description : ${mockProduct.description}`),
    ).toBeInTheDocument();
  });

  it("should render product details after loading", async () => {
    // Mock all axios calls
    axios.get.mockImplementation((url) => {
      if (url.includes("/api/v1/product/get-product/")) {
        return Promise.resolve({
          data: {
            product: mockProduct,
            success: true,
          },
        });
      }
      if (url.includes("/api/v1/category/get-category")) {
        return Promise.resolve({
          data: { category: [] },
        });
      }
      if (url.includes("/api/v1/product/related-product/")) {
        return Promise.resolve({
          data: { products: mockSimilarProducts },
        });
      }
      return Promise.reject(new Error("Not mocked"));
    });

    await act(async () => {
      render(
        <MemoryRouter initialEntries={["/product/test-product"]}>
          <Routes>
            <Route path="/product/:slug" element={<ProductDetails />} />
          </Routes>
        </MemoryRouter>,
      );
    });

    // Wait for product to load
    await waitFor(() => {
      expect(
        screen.getByText(`Name : ${mockProduct.name}`),
      ).toBeInTheDocument();
    });

    // Check all product details
    expect(screen.getByText(`Name : ${mockProduct.name}`)).toBeInTheDocument();
    expect(
      screen.getByText(`Description : ${mockProduct.description}`),
    ).toBeInTheDocument();
    expect(
      screen.getByText(`Category : ${mockProduct.category.name}`),
    ).toBeInTheDocument();
  });
  it("should render ProductNotFound component when API returns empty product", async () => {
    // Mock axios to return success but empty product
    axios.get.mockImplementation((url) => {
      if (url.includes("/api/v1/product/get-product/")) {
        return Promise.resolve({
          data: {
            success: true,
            product: null, // Empty product
          },
        });
      }
      if (url.includes("/api/v1/category/get-category")) {
        return Promise.resolve({ data: { category: [] } });
      }
      return Promise.reject(new Error("Not mocked"));
    });

    await act(async () => {
      render(
        <MemoryRouter initialEntries={["/product/empty-product"]}>
          <Routes>
            <Route path="/product/:slug" element={<ProductDetails />} />
          </Routes>
        </MemoryRouter>,
      );
    });

    await waitFor(() => {
      // Check for your ProductNotFound component content
      expect(screen.getByText(/Oops ! Page Not Found/i)).toBeInTheDocument();
    });
  });

  it("should handle API errors gracefully", async () => {
    // Mock axios to reject
    axios.get.mockImplementation((url) => {
      if (url.includes("/api/v1/category/get-category")) {
        return Promise.resolve({
          data: { category: [] },
        });
      }
      return Promise.reject(new Error("API Error"));
    });

    // Mock console.error to avoid test noise
    const consoleSpy = jest
      .spyOn(console, "error")
      .mockImplementation(() => {});

    await act(async () => {
      render(
        <MemoryRouter initialEntries={["/product/test-product"]}>
          <Routes>
            <Route path="/product/:slug" element={<ProductDetails />} />
          </Routes>
        </MemoryRouter>,
      );
    });

    // Wait for loading to finish (even though it failed)
    await waitFor(() => {
      expect(screen.queryByText(/Loading.../i)).not.toBeInTheDocument();
    });

    // Check that no product details are shown (since loading failed)
    expect(
      screen.queryByText(`Name : ${mockProduct.name}`),
    ).not.toBeInTheDocument();

    consoleSpy.mockRestore();
  });
});
